temp=document.getElementById("doing");
x=temp.getContext("2d");
temp.style.backgroundColor="gray";
next=0;
setInterval(_goahead,0)
shots=[];
shot=class{
    constructor(speed,angle,path)
    {
        this.x=temp.width/2;
        this.y=temp.height-20;
        this.speed=speed;
        this.angle=angle;
        this.path=path;
    }
    show()
    {
        x.beginPath();
        x.save()
        x.rotate(this.angle*(Math.PI/180));
        x.rect(this.x,this.y,5,20);
        x.restore();
        x.strokeStyle="white";
        x.stroke();
        x.closePath();
        this.y-=this.speed*Math.sin(this.angle);
        this.x-=this.speed*Math.cos(this.angle);
        if(this.y<=0||this.x<=0||this.x>temp.width)
        {
            this.y=temp.height-20;
            this.x=temp.width/2;
        }
    }
}

function _goahead()
{
    x.clearRect(0,0,temp.width,temp.height);
    angles=[45,30,15,5,-5,-15,-30,-45]; 
    if(shots.length==0)
    {   
        for(i=1;i<=10;i++)
        {
            diracetion=Math.round(Math.random()*7);
            shots.push(new shot(Math.random()*(1-0.2)+0.2, angles[diracetion]));
        }
    }
    shots.forEach(function(next) {
        diracetion=Math.round(Math.random()*7);
        //next.angle=angles[diracetion];
        next.show();
    });
}
